
CCAA = [
    "Castilla y leon, Spain",
    "Andalucia, Spain",
    "Castilla la mancha, Spain",
    "Aragon, Spain",
    "Extremadura, Spain",
    "Cataluna, Spain",
    "Galicia, Spain",
    "Comunidad valenciana, Spain",
    "Region de murcia, Spain",
    "Principado de asturias",
    "Navarra, Spain",
    "Comunidad de madrid, Spain",
    "Cantabria, Spain",
    "La rioja, Spain",
    "Portugal",
    "Euskadi, Spain"
]

USA = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "NewHampshire",
    "NewJersey",
    "NewMexico",
    "NewYork",
    "NorthCarolina",
    "NorthDakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "RhodeIsland",
    "SouthCarolina",
    "SouthDakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "WestVirginia",
    "Wisconsin",
    "Wyoming"]
