
spanish_comunities = [
    "Castilla y leon, Spain",
    "Andalucia, Spain",
    "Castilla la mancha, Spain",
    "Aragon, Spain",
    "Extremadura, Spain",
    "Cataluna, Spain",
    "Galicia, Spain",
    "Comunidad valenciana, Spain",
    "Region de murcia, Spain",
    "Principado de asturias",
    "Navarra, Spain",
    "Comunidad de madrid, Spain",
    "Cantabria, Spain",
    "La rioja, Spain",
    "Portugal",
    "Euskadi, Spain"
]

USA_STATES = [
    "West Virginia",
    "Illinois",
    "Maryland",
    "Idaho",
    "Vermont",
    "Connecticut",
    "New Mexico",
    "New Jersey",
    "Nebraska",
    "Pennsylvania",
    "Georgia",
    "Colorado",
    "South Carolina",
    "Oklahoma",
    "North Dakota",
    "Kentucky",
    "Nevada",
    "Arkansas",
    "Kansas",
    "South Dakota",
    "Virginia",
    "Iowa",
    "Arizona",
    "Rhode Island",
    "New Hampshire",
    "North Carolina",
    "Delaware",
    "California",
    "Wisconsin",
    "Oregon",
    "Washington",
    "Louisiana",
    "Utah",
    "Ohio",
    "Texas",
    "Tennessee",
    "New York",
    "Maine",
    "Michigan",
    "Montana",
    "Indiana",
    "Massachusetts",
    "District of Columbia",
    "Wyoming",
    "Mississippi",
    "Florida",
    "Minnesota",
    "Alabama",
    "Missouri"
]
